version: '2.4'
services:
  agent-alpine:
    image: amplify-agent-alpine
    volumes:
    - ../:/amplify
    tty: true
    networks:
      - controller-backend
networks:
  controller-backend:
    external: true
