version: '2.4'
services:
  agent-centos6:
    image: amplify-agent-centos6
    volumes:
    - ../:/amplify
    tty: true
    networks:
      - controller-backend
networks:
  controller-backend:
    external: true
