version: '2.4'
services:
  agent-debian8:
    image: amplify-agent-debian8
    volumes:
    - ../:/amplify
    tty: true
    networks:
      - controller-backend
networks:
  controller-backend:
    external: true
