version: '2.4'
services:
  agent-ubuntu1604-mysql8:
    image: amplify-agent-ubuntu1604-mysql8
    volumes:
    - ../:/amplify
    - /var/lib/mysql
    tty: true
    networks:
      - controller-backend
networks:
  controller-backend:
    external: true
